#! /bin/sh

bspc desktop ^1 -n I
bspc monitor -a II III IV V VI VII VIII IX X

bspc rule -a Gimp -d ^8 --follow --floating

bspc config border_width        2
bspc config window_gap          8
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focused_border_color '#45A5FF'
bspc config normal_border_color  '#444444'
bspc config urgent_border_color  '#FF0000'
bspc config presel_border_color  '#ff00ff'

bspc config top_padding 18
~/mybar/mybar.sh &